### ISSUE TITLE
maximum costs for changing names

### ISSUE THREAD

**Issue by SurfingNerd** [DMDcoin/diamond-contracts-registry#2]
The costs for changing names doubles every time the name is changed.
There should be an upper limit of 256 DMD as maximum cost.

**Comment by cryptonit** [comment]
sooner or later the question will arise if u can change owenrship of a name

maybe we should consider adding the option of transfer name with destination address when u choose a new name

so when u set a new name u can reserve the old one for a grace time of lets say 1 month

in that timeframe only the destination address can register that name 

after that timeframe every address can

would solve ninja claiming of names after the set to be free again

wont solve save payment between seller and buyer but thats not something we as blockchain operators should be involved in

3rd party contracts are possible to set the renaming process only if target party deposit some coin as payment
